### ISSUE TITLE
ROS2 Compatibility

### ISSUE THREAD

**Issue by roger-strain** [ros-drivers/microstrain_3dmgx2_imu#12]
We're doing some work on ROS2 for some of our projects now, and are planning on using devices this driver supports. Has any work been done on a ROS2 port yet? If not, we're going to be working on that shortly and will be happy to provide a PR.

**Comment by roger-strain** [comment]
We've got an initial PR ready for this. I assume it should go into a dashing-devel branch. Would you like me to just target the PR against indigo for now so you can take a look?

**Comment by roger-strain** [comment]
@chadrockey @tonybaltovski Looks like you guys have most of the (semi-)recent activity on this repo. Is this port something you guys would like to take a look at?

**Comment by tonybaltovski** [comment]
Thanks for that and sorry for being slow to reply.  I made a dashing branch to make a PR against.

**Comment by tonybaltovski** [comment]
Addressed via #13.
