### ISSUE TITLE
Missing explicit dependency and include on log4cxx

### ISSUE THREAD

**Issue by dirk-thomas** [ros-drivers/microstrain_3dmgx2_imu#3]
In the latest version of rosconsole the strict dependency on log4cxx has been removed. Now your package `microstrain_3dmgx2_imu` fails to build since it relied on the transitive dependency.

Please make the dependency on log4cxx explicit and import the necessary header file to unbreak the build on the farm (http://jenkins.ros.org/view/HbinP32/job/ros-hydro-microstrain-3dmgx2-imu_binarydeb_precise_i386).

**Comment by chadrockey** [comment]
Resolved:

https://github.com/ros-drivers/microstrain_3dmgx2_imu/commit/46be476152091dcf8204f2fcf77928dd1f0823e6
