### ISSUE TITLE
Kinetic release

### ISSUE THREAD

**Issue by tonybaltovski** [ros-drivers/microstrain_3dmgx2_imu#7]
Can you please do a release for kinetic?

**Comment by HolmarSeffelgruber** [comment]
Hi Tony, did you get it to run?

**Comment by tonybaltovski** [comment]
Yup, are you having issues?

**Comment by HolmarSeffelgruber** [comment]
Yes, but it may be a problem with the device or the adapter from USB to RS232. How did you connect it?

**Comment by tonybaltovski** [comment]
USB

**Comment by HolmarSeffelgruber** [comment]
I got it working by setting the defaults on the IMU using the hard and soft iron calibration tool.

**Comment by tonybaltovski** [comment]
Was released.
